<?php

/**
 * Implements hook_form_alter().
 */

function site_api_key_form_system_site_information_settings_alter(&$form, $form_state, $form_id)
{
    $default_key = \Drupal::config('siteapikey.configuration');
    $site_api_key = $default_key->get('siteapikey');

    $form['site_information']['site_api_key'] = array(
        '#type' => 'textfield',
        '#title' => t('Site API Key'),
        '#default_value' => $site_api_key,
    );

    // Change submit button text into 'Update Configuration'
    $form['actions']['submit']['#value'] = t('Update configuration');

    $form['#submit'][] = 'site_api_key_update';
}



function site_api_key_update($form, &$form_state)
{   
    $updated_api_key = $form_state->getValue(['site_api_key']);
    if(!empty($updated_api_key)) { 
    $config = \Drupal::configFactory()->getEditable('siteapikey.configuration');
    $config->set('siteapikey', $updated_api_key);
    $config->save();
    } else {
        $config = \Drupal::configFactory()->getEditable('siteapikey.configuration');
        $config->set('siteapikey', 'No API Key yet');
        $config->save(); 
    }

    drupal_set_message("Site API Key has been saved to " . $updated_api_key);
}